# yaml-language-server: disable
# Product Descriptor for Feature Branch Workflow Scenario
# This file demonstrates User Story 1: Automate Workspace for New Data Product

product:
  name: "Customer Insights"
  owner_email: "data-team@company.com"
  domain: "Customer Analytics"

environments:
  dev:
    enabled: true
    capacity_type: "trial"
    capacity_id: "0749b635-c51b-46c6-948a-02f05d7fe177"  # Trial FTL64
    description: "Development workspace for Customer Insights"

git:
  organization: "${GITHUB_ORG}"
  repository: "${GITHUB_REPO}"
  feature_prefix: "feature"
  directory: "data_products/customer_insights"

automation:
  audit_reference: "TEST-SCENARIO"
