[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
# Pytest configuration
markers = [
    "real_fabric: Tests that create actual resources in Microsoft Fabric (run manually only)",
    "slow: Tests that take a long time to run",
    "integration: Integration tests",
    "timeout: Set a timeout for test execution",
]
# Don't run real_fabric tests by default
addopts = "-m 'not real_fabric'"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
