product:
  name: "Sales Analytics"
  owner_email: "sales-team@company.com"
  domain: "Sales Insights"

environments:
  dev:
    enabled: true
    capacity_type: "trial"
    description: "Development workspace for sales analytics"

git:
  organization: "${GITHUB_ORG}"
  repository: "${GITHUB_REPO}"
  feature_prefix: "feature"
  directory: "data_products/sales_analytics"

automation:
  audit_reference: "JIRA-67890"
