product:
  name: "Sample Data Product"
  owner_email: "owner@example.com"
  domain: "Customer Insights"

environments:
  dev:
    enabled: true
    capacity_type: "trial"
    description: "Development workspace for Sample Data Product"

git:
  organization: "${GITHUB_ORG}"
  repository: "${GITHUB_REPO}"
  feature_prefix: "feature"
  directory: "data_products/sample_data_product"

automation:
  audit_reference: "JIRA-000"
