name: reusable-lint
on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linters
        run: |
          pip install ruff black sqlfluff
      - name: Lint Python
        run: |
          ruff check .
          echo "Running black --diff to show changes:"
          black --diff init_new_project.py scenarios/config-driven-workspace/config_driven_workspace.py scenarios/automated-deployment/run_automated_deployment.py || true
          black --check .
      - name: Lint SQL
        run: |
          sqlfluff lint data/sql --dialect tsql || true
