name: reusable-test
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r ops/requirements.txt
          pip install pytest chispa
      - name: Run tests
        run: pytest -q || true
